apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  selector:
    app: jenkins-app  # لازم يكون نفس الـ Label اللي في الـ deployment.yaml
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010 # تقدري تفتحي الأبلكيشن من الـ IP بتاعك وبورت 30001
