$ANSIBLE_VAULT;1.1;AES256
66623734313936646630303361323563386664333266393030373266623762653061656235643264
3136373032653231643864376366313036653761333331300a653534393961346464333631363834
30393266393664303661383830353839363134383339356131343563643531396163373465366433
6230383264396333390a373366623164383531396335376336313935613762653839336264376135
37353037393065343732393065343139313365333838623231373364303535353638373163326461
64653764316430636632303938333065656637383932623632383839353537656463316536363166
34383137303161306266376266613234356261363765333737616162613631323161656262643264
32623634393834366132336464333931363335663331343334613366646630616230666531386334
36623065643065346131376137343231333231323537386133373762393465613738
